# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-28 15:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('admn_no', models.IntegerField()),
                ('password', models.CharField(max_length=30)),
                ('branch', models.CharField(max_length=30)),
                ('year', models.DateField()),
                ('access', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='RegisterModel',
        ),
    ]
