# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-29 03:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20160528_1644'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Table',
        ),
    ]
